[project]
name = "dmea-smarthub"
version = "0.1.0"
description = "A python library for fetching data from DMEA SmartHub"
readme = "README.md"
authors = [
    { name = "Chris Skalenda", email = "chris@skalenda.org" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx2>=2.12.0",
    "keyring>=25.7.0",
    "pydantic>=2.13.5",
    "typer>=0.27.2",
]

[project.scripts]
dmea-smarthub = "dmea_smarthub.cli:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.6",
    "ty>=0.0.78",
]
